language: node_js
node_js:
  - "stable"

before_install:
  - npm install -g sonar-scanner
  
cache:
  directories:
  - node_modules
script:
  - npm run test
  - npm run sonarqube -Dsonar.login=$SONAR_TOKEN
  - npm run build
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master